### ISSUE TITLE
Dataset please 

### ISSUE THREAD

**Issue by kailashg26** [Thijsvanede/Tiresias#2]
Hello, can you provide the data set if it is open sourced? That would be very helpful, thanks!

**Comment by Thijsvanede** [comment]
Hello,

Yes, this research was part of the [DeepCASE](https://vm-thijs.ewi.utwente.nl/static/homepage/papers/deepcase.pdf) paper, we used the same [datasets](https://github.com/Thijsvanede/DeepCASE/tree/main/data) in that research which can be found [here](https://github.com/Thijsvanede/DeepCASE/tree/main/data). Please note that the HDFS dataset is public, but the Lastline dataset is unfortunately not public.
